name: Build Android

on:
  push:
    branches:
      - main

jobs:   
  build:
    name: Creating release build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: npm install
      - run: cd android && ./gradlew clean  && ./gradlew assembleRelease
      
      - name: Push to Release
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: android/app/build/outputs/apk/release/*
