name: Build Android

on:
  push:
    branches:
      - main

jobs:   
  build:
    name: Creating release build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: npm install
      - run: chmod +x android/gradlew  # Ensure gradlew is executable
      - run: cd android && ./gradlew clean && ./gradlew assembleRelease

      - name: List Output Directory
        run: ls -R android/app/build/outputs

      - name: List Release APK Directory
        run: ls -R android/app/build/outputs/apk/release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: android/app/build/outputs/apk/release/*.apk

      - name: Find APK files
        run: find android/app/build/outputs -name "*.apk"

